# This is a sample config file that points to a solr server for each environment
development:
  url: http://localhost:8983/solr/hydra-development
test:
  url: <%= "http://localhost:#{ENV['TEST_JETTY_PORT'] || 8985}/solr/hydra-test" %>
production:
  url: <%= ENV["PLUM_SOLR_URL"] %>
staging:
  url: <%= ENV["PLUM_SOLR_URL"] %>
